namespace :elixir_overengineered do
  task :check do
    `which elixir`
    raise "Please ensure that you have elixir installed" unless $?.success?

    `which erl`
    raise "Please ensure that you have erlang installed" unless $?.success?
  end

  task :build => :check do
    path = File.dirname(__FILE__)
    `cd #{path}; make build`
  end
end
