namespace :sqlite do
  task :clean do
    `rm /tmp/unscramble_db`
    `rm /tmp/unscramble_dict.txt`
  end

  task :check do
    `which sqlite3`
    raise "Please ensure that you have sqlite3 installed" unless $?.success?
  end

  task :build => :check do
    # no-op
  end
end
