namespace :postgres do
  task :check do
    `which ruby`
    raise "Please ensure that you have ruby installed" unless $?.success?

    `which psql`
    raise "Please ensure that you have psql installed" unless $?.success?
  end

  task :build => :check do
    `createdb unscramble`
    `psql -d unscramble -f ./languages/postgres/setup-database.sql`

    puts "Indexing dictionary, this may take awhile..."
    load "./languages/postgres/store.rb"
  end
end
