namespace :Rust2 do
  task :check do
    File.exists?("#{File.dirname(__FILE__)}/target/release/unscramble") or raise "run cargo build --release"
  end

  task :build => :check do
    
    path = File.dirname(__FILE__)
    `cd #{path}; cp target/release/unscramble ./`
  end
end
