namespace :Rust2 do
  task :check do
    `which cargo`
    raise "Please ensure that you have Rust installed" unless $?.success?
  end

  task :build => :check do
    path = File.dirname(__FILE__)
    unless File.exists?("#{path}/unscramble")
      `cd #{path}; cargo build --release; cp target/release/unscramble ./`
    end
  end
end
