namespace :Swift do
  task :check do
    `which swiftc`
    raise "Please ensure that you have a valid Swift compiler" unless $?.success?
  end

  task :build => :check do
    path = File.dirname(__FILE__)
    `cd #{path}; swiftc Unscrambler.swift -o unscramble`
  end
end